title: "Shreyansh's ML/DL Blog"
description: "Explaining ML/DL papers and algorithms from scratch"
author: "Shreyansh Modi"
email: your@email.com
baseurl: "" # Leave this empty if using username.github.io
url: "https://shrrynsh.github.io"

theme: tessera-jekyll  # If this is in use, otherwise leave it out for custom theme

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num"

# Enable Math rendering (using MathJax)
mathjax: true

# Markdown options
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Social links (optional)

